---
title: "All Subjects per Sensor per Activity"
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---

```{r echo=FALSE, warning = FALSE, message = FALSE, results = "asis"} 
library(tidyverse) 
library(grid) 
library(gridExtra) 
library(scales) 
library(knitr) 
library(kableExtra) 
#install.packages("devtools") 
#devtools::install_github("kassambara/ggpubr") 
library(ggpubr) 
library(XLConnect) 
extrafont::loadfonts(quiet=TRUE) 


nsf_dir <- getwd()
raw_data_dir <- file.path(nsf_dir, 'raw-dataset')
final_data_dir <- file.path(nsf_dir, 'data')
log_dir <- file.path(nsf_dir, 'log-files')


log_file <- file.path(log_dir, paste0('filtered-subj-list-log-', format(Sys.Date(), format='%m-%d-%y'), '.txt'))
file.create(log_file)

super_session_pattern <- "^SuperSession$" 


# Point this to the dataframe generated by `SplitSessionAndMergeData.R`. 
# discarded_df <- read_csv("@Datasets/discarded_HR.csv", col_types = cols()) 



result_df <- tibble() 
emails_df <- tibble() 
subject_summary <- tibble() 
subjects_we_filtered <- tibble() 
qc1_filtered_subject <- tibble() 

file_name_extension <- ""
good_subj_list <- read.csv(file.path('data', 'subj_good_df.csv'))$Subject


# ****
# Change this to FALSE, if you want to generate raw data file
# Change this to TRUE, if you want to generate filtered(quality control phase 1) data file
is_filter_data = T


non_filtered_col_name <- c('Subject', 'Condition', 'Session', 'CovertedTime', 'TimeElapsed',
                        'PP.non.filtered', 'HR.non.filtered', 'BR.non.filtered', 'D.EDA.non.filtered',
                        'D.HR.non.filtered', 'N.EDA.non.filtered', 'N.HR.non.filtered', 'Task')




isMatch <- function(pattern, str) { 
  return(grepl(str, pattern)) 
} 

find_subject_sessions <- function() { 
  
  grp_list <- list.dirs(path=raw_data_dir, full.names=F, recursive=F) 

  invisible(sapply(grp_list, function(grp_name) { 
    grp_dir <- file.path(raw_data_dir, grp_name) 
    subj_list <- list.dirs(path=grp_dir, full.names=F, recursive=F) 
    
    sapply(subj_list, function(subj_name) { 
      subj_dir <- file.path(grp_dir, subj_name) 
      session_list <- list.dirs(path=subj_dir, full.names=F, recursive=F) 
      session_list_pp <- session_list[grepl(super_session_pattern, session_list, perl = TRUE)] 
      
      sapply(session_list_pp, function(session_name) { 
        session_dir <- file.path(subj_dir, session_name) 
        
        tryCatch({ # in case there are errors in the number of sessions 
          
          if(subj_name %in% good_subj_list) {
            process_the_subject(session_dir, subj_name)
          }
          
        }, warning = function(w) { 
          message(paste0("Warnings present for subject ", subj_name, ": ", w, " Continuing process anyway.")) 
          flush.console() 
          return() 
        }, error = function(e) { 
          message(paste0("Error present for subject ", subj_name, ": ", e, " ")) 
          flush.console() 
          return() 
        }) 
      }) 
    }) 
  })) 
} 




process_the_subject <- function(session_dir, subj_name) { 
  pp_file_pattern <- ".*_merged.csv" 
  pp_file_name <- list.files(path=session_dir, pattern=pp_file_pattern, recursive=F) 
  
  subj_interface_file_pattern <- paste0('^[^~].*-', subj_name, '.xlsx')  
  subj_interface_file_name <- list.files(path=session_dir, pattern=subj_interface_file_pattern, recursive=F) 
  
  if (length(pp_file_name) == 0 || pp_file_name == "") { 
    stop(paste0("Session file for subject ", subj_name, " is empty. ")) 
  } 
  
  df <- read_csv(file.path(session_dir, pp_file_name), col_types = cols()) 
  df$Session <- factor(df$Session, levels = c("RestingBaseline", "BaselineWriting", "StressCondition", "DualTask", "Presentation")) 
  
  if (nrow(df) < 4) { 
    message(paste0("Dataframe for subject ", subj_name, " is empty. ")) 
    flush.console() 
    return() 
  } 
  
  df <- df[ , !(names(df) %in% c("Time", "Perspiration"))] 
  for (col in c("CovertedTime", "NR_Perspiration", "HR_z", "BR_z", "Session", "EDA_i", "HR_i", "EDA_l", "HR_l", "HR", "EDA")) { 
    if (!(any(names(df) == col))) { 
      df[[col]] <- NA 
    } 
  } 
  
  condition <- NA 
  if (isMatch(subj_interface_file_name, "intermittent-high")) { 
    condition <- "IH" 
  } else if (isMatch(subj_interface_file_name, "batch-high")) { 
    condition <- "BH" 
  } else if (isMatch(subj_interface_file_name, "intermittent-low")) { 
    condition <- "IL" 
  } else if (isMatch(subj_interface_file_name, "batch-low")) { 
    condition <- "BL" 
  } 
  
  df$Subject = subj_name 
  df$Condition = condition 
  
  result_df <<- rbind(result_df, df) 
  subj_interface_df <- readWorksheet(XLConnect::loadWorkbook(file.path(session_dir, subj_interface_file_name)), sheet = 'Sheet1') 
  
  email_times_we_want <- c("Email.1.Open.Email.Time", "Email.2.Open.Email.Time", "Email.3.Open.Email.Time", "Email.4.Open.Email.Time", 
                           "Email.5.Open.Email.Time", "Email.6.Open.Email.Time", "Email.7.Open.Email.Time", "Email.8.Open.Email.Time", 
                           "Email.1.Ending.Time", "Email.2.Ending.Time", "Email.3.Ending.Time", "Email.4.Ending.Time", "Email.5.Ending.Time", 
                           "Email.6.Ending.Time", "Email.7.Ending.Time", "Email.8.Ending.Time") 
  
  for (email_time in email_times_we_want) { 
    if (!(email_time %in% names(subj_interface_df))) { 
      subj_interface_df[[email_time]] <- NA 
    } 
  } 
  
  subj_interface_df <- subj_interface_df[1, email_times_we_want] 
  subj_interface_df$Subject <- subj_name 
  
  if (nrow(emails_df) > 0) { 
    emails_df <<- rbind(emails_df, subj_interface_df) 
  } else { 
    emails_df <<- subj_interface_df 
  } 
} 


circus_wrangler <- function() { 
  names(result_df) <<- c("CovertedTime", "PP", "HR", "BR", "Session", "D.EDA", "D.HR", "N.EDA", "N.HR", "HR_bad", "EDA_bad", "Subject", "Condition") 
  
  result_df$N.EDA[is.na(result_df$N.EDA)] <<- result_df$EDA_bad[is.na(result_df$N.EDA)] 
  result_df$N.HR[is.na(result_df$N.HR)] <<- result_df$HR_bad[is.na(result_df$N.HR)] 
  result_df <<- result_df[ , !(names(result_df) %in% c("EDA_bad", "HR_bad"))] 
} 


do_the_actual_plotting_now <- function(df, col_name, condition) { 
  
  label <- figure_out_labels(col_name) 
  df <- result_df[ , c("CovertedTime", "Session", "Subject", "Condition", col_name)] 
  
  df <- df %>% 
      filter(Condition == condition) %>% 
      na.omit() %>% 
      group_by(Subject, Session) %>% 
      arrange(CovertedTime) %>% 
      mutate(TimeElapsed = as.integer(CovertedTime) - as.integer(head(CovertedTime, 1))) 
  
  if (nrow(df) > 0) { 
    
    df[[col_name]] <- as.numeric(df[[col_name]]) 
    
    sessions <- levels(df$Session) 
    for (sess in sessions) { 
      
      title_sess <- figure_out_session(sess) 
      n <- length(levels(factor((df %>% filter(Session == sess))$Subject))) 
      
      
      
      
      ##########################################################################################################
      #####                                         ***PLOTS***                                            ##### 
      ##########################################################################################################
      # g1 <- df %>% 
      #   filter(Session == sess) %>% 
      #   ggplot(aes_string(x = "TimeElapsed", y = col_name, color = "Subject")) + 
      #     geom_line(alpha = 0.9) + 
      #     labs(title = paste0(get_condition(condition), ": ", col_name, " for ", title_sess), 
      #         subtitle = bquote(list(italic('n')==.(n))), 
      #         x = "Time [s]", 
      #         y = label) + 
      #     theme_bw() + 
      #     theme(panel.background=element_rect(fill = "NA"), panel.grid.minor = element_line(colour = "#E0E0E0"), 
      #           plot.title = element_text(size=10)) + 
      #     scale_x_continuous(breaks = pretty_breaks(n = 4)) 
      ###########################################################################################################
      
      
      bad_subjects <- NULL 
      filtered_df <- as.data.frame(df) 
      
      #############################################################################################
      #### CHANGE THIS - Data Filtering - V.V.I. - ****
      #############################################################################################
      if (is_filter_data==T) {
        if (grepl('HR', col_name)) {
          filtered_df <- filtered_df %>% filter(filtered_df[[col_name]] < 40 | filtered_df[[col_name]] > 140)
        } else if (grepl('BR', col_name)) {
          filtered_df <- filtered_df %>% filter(filtered_df[[col_name]] < 4 | filtered_df[[col_name]] > 40)
        } else if (grepl('EDA', col_name)) {
          filtered_df <- filtered_df %>% filter(filtered_df[[col_name]] < 0.01 | filtered_df[[col_name]] > 100)
        } else {
          filtered_df <- filtered_df[filtered_df[[col_name]] == 0, ]
        }
      }
      #############################################################################################
      
      
      #############################################################################################
      #### CHANGE THIS - Data Filtering - V.V.I. - ****
      #############################################################################################
      # We add subjects to `bad_subjects` who have signals that hit 0 even once! We are ruthless.
      # filtered_df <- filtered_df[filtered_df[[col_name]] == 0, ]
      #############################################################################################
      
      bad_subjects <- levels(factor((filtered_df %>% filter(Session == sess))[ , "Subject"])) 
      
      
      if (col_name == "PP" & condition == "BL" & sess == "StressCondition") {
        bad_subjects <- c(bad_subjects, "T113")
      }
      
      if (col_name == "PP" & condition == "IL" & sess == "Presentation") {
        bad_subjects <- c(bad_subjects, "T031")
      }
      
      # Half time Chest HR signal missing
      # add_bad_signal('T031', 'DT', 'HR', 'Bad', 'Half time signal missing')
      if (col_name == "HR" & condition == "IL" & sess == "DualTask") {
        bad_subjects <- c(bad_subjects, "T031")
      }
      
      filtered_df <- filtered_df %>% 
        filter(Session == sess & !(Subject %in% bad_subjects)) 
        
      filtered_subject <- tibble("Subject" = bad_subjects, "Session" = sess, "Measure" = col_name) 
      if (nrow(subjects_we_filtered) > 0) { 
        subjects_we_filtered <<- rbind(subjects_we_filtered, filtered_subject) 
      } else { 
        subjects_we_filtered <<- filtered_subject 
      } 
      
      
      ##########################################################################
      #### CHANGE THIS - Data Filtering - V.V.I. - ****
      # # ... and now for the global tibble. Goodbye bad subjects (they are now NA here)! 
      if (is_filter_data==T) {
        result_df[result_df$Subject %in% bad_subjects & result_df$Session == sess, col_name] <<- NA
      }
      ##########################################################################
      
      
      for (subj_name in bad_subjects) {
        temp_qc1_filtered_subject <- tibble("Subject"=subj_name, 
                                            "Session"=sess, 
                                            "Measure"=col_name,
                                            "Explanation"='Filtered out whole session signal')
        qc1_filtered_subject <<- rbind(qc1_filtered_subject, temp_qc1_filtered_subject) 
        
        # if (nrow(subjects_we_filtered) > 0) { 
        #   qc1_filtered_subject <<- rbind(qc1_filtered_subject, temp_qc1_filtered_subject) 
        # } else { 
        #   qc1_filtered_subject <<- temp_qc1_filtered_subject 
        # } 
        
        # message(paste0(subj_name, "'s ", col_name, " signal for ", sess, " has been removed. "))
        # write(paste0(subj_name, "'s ", col_name, " signal for ", sess, " has been removed. "), file=log_file, append=TRUE)
      }
      
      n <- length(levels(factor((filtered_df %>% filter(Session == sess))$Subject))) 
      
      
      
      ##########################################################################################################
      #####                                         ***PLOTS***                                            ##### 
      ##########################################################################################################
      # g2 <- filtered_df %>% 
      #   ggplot(aes_string(x = "TimeElapsed", y = col_name, color = "Subject")) + 
      #     geom_line(alpha = 0.9) + 
      #     labs(title = paste0(get_condition(condition), ": ", col_name, " for ", title_sess, ": Filtered "), 
      #         subtitle = bquote(list(italic('n')==.(n))), 
      #         x = "Time [s]", 
      #         y = label) + 
      #     theme_bw() + 
      #     theme(panel.background=element_rect(fill = "NA"), panel.grid.minor = element_line(colour = "#E0E0E0"), 
      #           plot.title = element_text(size=10)) + 
      #     scale_x_continuous(breaks = pretty_breaks(n = 4)) 
      # 
      # 
      # ### We now print the two plots side by side. 
      # print(ggarrange(g1, g2, ncol = 2, nrow = 1)) 
      # 
      # ### And print a little space between them. 
      # cat("  \n    \n    \n  ") 
      ##########################################################################################################     
      
    } 
  } 
} 


figure_out_session <- function(sess) { 
  if (isMatch(sess, 'RestingBaseline')) { 
    return("Resting Baseline") 
  } else if (isMatch(sess, 'BaselineWriting')) { 
    return("Single Task") 
  } else if (isMatch(sess, 'StressCondition')) { 
    return("Break") 
  } else if (isMatch(sess, 'DualTask')) { 
    return("Dual Task") 
  } 
  return(sess) 
} 



figure_out_labels <- function(col_name) { 
  if (isMatch(col_name, 'PP')) { 
    return(bquote(paste('Perinasal Perspiration [',''^'o','C',''^2,']'))) 
  } else if (isMatch(col_name, 'HR')) { 
    return('Heart Rate [BPM]') 
  } else if (isMatch(col_name, 'BR')) { 
    return('Breathing Rate [BPM]') 
  } else if (isMatch(col_name, 'EDA')) { 
    return(expression(paste('EDA [', mu, 'S]'))) 
  } 
  return('Unknown axis.') 
} 



get_condition <- function(condition) { 
  if (isMatch(condition, 'IH')) { 
    return("IF") 
  } else if (isMatch(condition, 'IL')) { 
    return("IN") 
  } else if (isMatch(condition, 'BH')) { 
    return("BF") 
  } else if (isMatch(condition, 'BL')) { 
    return("BN") 
  } 
  return('Unknown condition') 
} 

``` 

```{r echo=FALSE, warning = FALSE, message = FALSE} 
find_subject_sessions() 
circus_wrangler() 
``` 

\newpage  
\vspace*{\fill} 
# Intermittent-Filler (IF) 
\vspace*{\fill} 
\newpage  
```{r echo = FALSE, warning = FALSE, message = FALSE} 
measurements <- c("PP", "HR", "BR", "D.EDA", "D.HR", "N.EDA", "N.HR") 
condition <- "IH" 
for (measure in measurements) { 
  do_the_actual_plotting_now(result_df, measure, condition) 
} 
``` 

\newpage  
\vspace*{\fill} 
# Intermittent-Nothing (IN) 
\vspace*{\fill} 
\newpage  
```{r echo = FALSE, warning = FALSE, message = FALSE} 
condition <- "IL" 
for (measure in measurements) { 
  do_the_actual_plotting_now(result_df, measure, condition) 
} 
``` 

\newpage  
\vspace*{\fill} 
# Batch-Filler (BF) 
\vspace*{\fill} 
\newpage  
```{r echo = FALSE, warning = FALSE, message = FALSE} 
condition <- "BH" 
for (measure in measurements) { 
  do_the_actual_plotting_now(result_df, measure, condition) 
} 
``` 

\newpage  
\vspace*{\fill} 
# Batch-Nothing (BN) 
\vspace*{\fill} 
\newpage  
```{r echo = FALSE, warning = FALSE, message = FALSE} 
condition <- "BL" 
for (measure in measurements) { 
  do_the_actual_plotting_now(result_df, measure, condition) 
} 
``` 

```{r echo = FALSE, warning = FALSE, message = FALSE} 
result_df <- result_df[ , c("Subject", "Condition", "Session", "CovertedTime", "PP", "HR", "BR", "D.EDA", "D.HR", "N.EDA", "N.HR")] 
result_df <- result_df %>% 
  group_by(Subject, Session) %>% 
  mutate(TimeElapsed = as.integer(CovertedTime) - as.integer(head(CovertedTime, 1))) 



#### CHANGE THIS - Data Filtering - V.V.I. - ****
if (is_filter_data==T) {
  result_df[result_df$Subject=="T092" & 
              result_df$Session=="RestingBaseline" &
              result_df$TimeElapsed >= 0 &
              result_df$TimeElapsed <= 34,
              'HR'] <- NA
}


result_df$Task <- NA 
result_df[result_df$Session == "DualTask", "Task"] <- "Essay" 

subj_list <- levels(factor((result_df$Subject))) 
for (subject in subj_list) { 

  subj_email_df <- emails_df %>% 
    filter(Subject == subject) 
  
  if (nrow(subj_email_df) == 0) { 
    result_df[result_df$Subject == subject & result_df$Session == "DualTask", "Task"] <- NA 
  } 
  
  condition <- as.character(result_df[result_df$Subject == subject, "Condition"][1, 1]) 
  bad_counter <- 0 
  if (condition %in% c("IH", "IL")) { 
    for (i in 1:8) { # since there are 8 emails 
      if (is.na(subj_email_df[[i]]) | is.na(subj_email_df[[i + 8]]) | subj_email_df[[i]] == 0 | 
          subj_email_df[[i + 8]] == 0 | subj_email_df[[i]] == subj_email_df[[i + 8]]) { 
        bad_counter <- bad_counter + 1 
        next 
      } 
      result_df[result_df$Subject == subject & result_df$Session == "DualTask" & 
                  subj_email_df[[i]] <= result_df$TimeElapsed & result_df$TimeElapsed <= subj_email_df[[i + 8]], "Task"] <- "Email" 
    } 
    if (bad_counter == 8) { 
      result_df[result_df$Subject == subject & result_df$Session == "DualTask", "Task"] <- NA 
    } 
  } else if (condition %in% c("BH", "BL")) { 
    min_time <- apply(subj_email_df[subj_email_df$Subject == subject, 1:16], 1, FUN = min) 
    max_time <- apply(subj_email_df[subj_email_df$Subject == subject, 1:16], 1, FUN = max) 
    if (!is.na(min_time) & !is.na(min_time) & max_time != 0 & min_time != max_time) { 
      result_df[result_df$Subject == subject & result_df$Session == "DualTask" & 
                  min_time <= result_df$TimeElapsed & result_df$TimeElapsed <= max_time, "Task"] <- "Email" 
    } else { 
      result_df[result_df$Subject == subject & result_df$Session == "DualTask", "Task"] <- NA 
    }
  } 
} 

result_df <- result_df[ , c("Subject", "Condition", "Session", "CovertedTime", "TimeElapsed", "PP", "HR", "BR", "D.EDA", "D.HR", "N.EDA", "N.HR", "Task")] 
emails_df <- emails_df[ , c("Subject", "Email.1.Open.Email.Time", "Email.2.Open.Email.Time", "Email.3.Open.Email.Time", "Email.4.Open.Email.Time", 
                           "Email.5.Open.Email.Time", "Email.6.Open.Email.Time", "Email.7.Open.Email.Time", "Email.8.Open.Email.Time", 
                           "Email.1.Ending.Time", "Email.2.Ending.Time", "Email.3.Ending.Time", "Email.4.Ending.Time", "Email.5.Ending.Time", 
                           "Email.6.Ending.Time", "Email.7.Ending.Time", "Email.8.Ending.Time")] 



#### CHANGE THIS - Data Filtering - V.V.I. - ****
###################################################################################################################
# write.table(result_df, file = paste0("@Datasets/full_df_non_filtered", file_name_extension, ".csv"),
#             col.names=non_filtered_col_name, row.names=F, sep = ',')
# 
# write.table(result_df, file = paste0(file.path(final_data_dir, "full_df_non_filtered"), file_name_extension, ".csv"),
#             col.names=non_filtered_col_name, row.names=F, sep = ',')
# 
# mean_df <- result_df %>%
#     select(-CovertedTime, -TimeElapsed, -Task) %>%
#     group_by(Subject,	Session, Condition) %>%
#     summarize_all(mean, na.rm=T) %>%
#     ungroup()
# 
#   print(str(mean_df))
#   colnames(mean_df) <- c('Subject', 'Session', 'Condition', 'PP', 'HR', 'BR', 'D.EDA', 'D.HR', 'N.EDA', 'N.HR')
#   print(str(mean_df))
# 
#   write.table(mean_df, file = file.path("@Datasets/result_df_non_filtered.csv"), row.names=F, sep = ',')
#   write.table(mean_df, file = file.path(final_data_dir, "result_df_non_filtered.csv"), row.names=F, sep = ',')
###################################################################################################################


###############################################################################################################
if (is_filter_data==T) {
  write.table(result_df, file = paste0(file.path(final_data_dir, "full_df_first_phase_filtered"),
                                       file_name_extension, ".csv"), row.names=F, sep = ',')
  write.table(qc1_filtered_subject, 
              file = paste0(file.path(final_data_dir, "bad_signal_first_phase"), file_name_extension, ".csv"), 
              row.names=F, 
              sep = ',')
  
  
  signal_list <- c("PP", "BR", "N.EDA", "HR", "N.HR")
  filtered_subject_no_df <- qc1_filtered_subject %>% 
    filter(Measure %in% signal_list) %>% 
    rename(Signal=Measure) %>% 
    group_by(Signal, Session) %>% 
    summarise(QC1=n()) %>% 
    arrange(match(Signal, signal_list))
  write.table(filtered_subject_no_df, 
              file = paste0(file.path(final_data_dir, "filtered_subject_no_qc1"), file_name_extension, ".csv"), 
              row.names=F, 
              sep = ',')
  
  
  mean_df <- result_df %>%
      select(-CovertedTime, -TimeElapsed, -Task) %>%
      group_by(Subject,	Session, Condition) %>%
      summarize_all(mean, na.rm=T) %>%
      ungroup()
  
  write.table(mean_df, file = file.path(final_data_dir, "result_df_first_phase.csv"), row.names=F, sep = ',')

  } else {
    
  write.table(result_df, file = paste0(file.path(final_data_dir, "full_df_non_filtered"), 
                                       file_name_extension, ".csv"),
              col.names=non_filtered_col_name, 
              row.names=F, sep = ',')
  
  mean_df <- result_df %>%
      select(-CovertedTime, -TimeElapsed, -Task) %>%
      group_by(Subject,	Session, Condition) %>%
      summarize_all(mean, na.rm=T) %>%
      ungroup()
  
    print(str(mean_df))
    colnames(mean_df) <- c('Subject', 'Session', 'Condition', 'PP', 'HR', 'BR', 'D.EDA', 'D.HR', 'N.EDA', 'N.HR')
    print(str(mean_df))
  
    write.table(mean_df, file = file.path(final_data_dir, "result_df_non_filtered.csv"), row.names=F, sep = ',')
}


###############################################################################################################











# write.table(result_df, file = "@Datasets/physiological_data.csv", row.names=F, sep = ',') 
# write.table(emails_df, file = "@Datasets/email_df.csv", row.names=F, sep = ',') 
``` 

```{r echo = FALSE, warning = FALSE, message = FALSE} 
measurements <- c("PP", "HR", "BR", "D.EDA", "N.EDA", "D.HR", "N.HR") 
for (measure in measurements) { 
  result_df[[measure]] <- as.numeric(result_df[[measure]]) 
} 
subjects_we_filtered$Explaination <- "Filtered in All Signals" 

# if (nrow(subjects_we_filtered) > 0) { 
#   subjects_we_filtered <- unique(rbind(discarded_df, subjects_we_filtered)) 
# } else { 
#   subjects_we_filtered <- unique(discarded_df) 
# } 

subject_summary <- result_df[ , !names(result_df) %in% c("TimeElapsed", "CovertedTime", "Task")] %>% 
  group_by(Subject,	Session, Condition) %>% 
  summarize_all(mean, na.rm = TRUE) %>% 
  ungroup() 

subject_summary <- as.tibble(subject_summary) 

for (measure in measurements) { 
  subject_summary[!is.na(subject_summary[[measure]]), measure] <- 1 
} 

subject_summary[is.na(subject_summary)] <- 0 

for (subj_name in levels(factor(subject_summary$Subject))) { 
  for (measure in measurements) { 
    specific_subject_filter_measure_combo <- subjects_we_filtered %>% 
      filter(Measure == measure) 
    
    do_we_have_anything_now <- specific_subject_filter_measure_combo %>% 
      filter(Subject == subj_name) 
    
    if (nrow(do_we_have_anything_now) > 0) { 
      subject_summary[subject_summary$Subject == subj_name & subject_summary$Session %in% do_we_have_anything_now$Session, measure] <- -1 
    } 
  } 
} 

for (subj_name in unique(subjects_we_filtered$Subject)) { 
  if (!(subj_name %in% subject_summary$Subject)) { 
    subject_summary <- rbind(subject_summary, tibble("Subject" = subj_name, 
                                                     "Session"	= c("RestingBaseline", "BaselineWriting", "StressCondition", "DualTask", "Presentation"), 
                                                     "Condition"	= -1, "PP" = -1, "HR" = -1, "BR" = -1, "D.EDA" = -1, "D.HR" = -1, "N.EDA"	= -1, "N.HR" = -1)) 
  } 
} 

subject_summary <- subject_summary %>% 
  mutate(Session = factor(Session, levels = c("RestingBaseline", "BaselineWriting", "StressCondition", "DualTask", "Presentation"))) %>% 
  arrange(Subject, Session) 

subject_summary <- rbind(subject_summary, tibble("Subject" = paste0("TOTAL: ", length(unique(subject_summary$Subject))), 
                                                 "Session"	= "-----", 
                                                 "Condition"	= "--", 
                                                 "PP" = sum(subject_summary$PP == 1), 
                                                 "HR" = sum(subject_summary$HR == 1), 
                                                 "BR" = sum(subject_summary$BR == 1), 
                                                 "D.EDA" = sum(subject_summary$D.EDA == 1), 
                                                 "D.HR" = sum(subject_summary$D.HR == 1), 
                                                 "N.EDA"	= sum(subject_summary$N.EDA == 1), 
                                                 "N.HR" = sum(subject_summary$N.HR == 1))) 

subjects_we_filtered <- subjects_we_filtered %>% 
  mutate(Session = factor(Session, levels = c("RestingBaseline", "BaselineWriting", "StressCondition", "DualTask", "Presentation"))) %>% 
  arrange(Subject, Session) 

subject_summary$IRB <- "Unknown" 

# write.table(subject_summary, file = "@Datasets/subject_summary.csv", row.names=F, sep = ',')
# write.table(subjects_we_filtered, file = "@Datasets/subjects_we_filtered.csv", row.names=F, sep = ',')
``` 
